apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: prisma-migrate
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: IMAGE_TO_REPLACE
          command: ['/bin/sh', '-c']
          args:
            - npx prisma migrate deploy
          envFrom:
            - secretRef:
                name: api-gateway-env
