apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: 'glavito-platform'
      auth:
        workloadIdentity:
          clusterLocation: 'us-central1-a'
          clusterName: 'glavito-cluster'
          serviceAccountRef:
            name: 'external-secrets-sa'
            namespace: 'external-secrets'
