apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: alibaba-store
spec:
  provider:
    alibaba:
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: alibaba-access-key
            key: accessKeyID
            namespace: external-secrets
          accessKeySecretSecretRef:
            name: alibaba-access-key
            key: accessKeySecret
            namespace: external-secrets
      region: me-east-1

