apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - admin/deployment.yaml
  - admin/service.yaml
  - admin/hpa.yaml
  - api/deployment.yaml
  - api/service.yaml
  - api/hpa.yaml

